<template>
  <Aside :activeIndex="activeIndex" :title="title" :items="items"></Aside>
</template>

<script>
  import Aside from '../ThreeAside'
  export default {
    data(){
      return{
        activeIndex:'/zongzhi/organ/institution',
        title:'综治平台',
        items:[
          {
            index:'1',
            title:'综治组织',
            subs:[
              {
                index:'/zongzhi/organ/institution',
                title:'综治机构'
              },
              {
                index:'/zongzhi/organ/group',
                title:'群防群治组织'
              },
              {
                index:'#222',
                title:'网络队伍',
                subs:[
                  {
                    index:'/zongzhi/organ/network/long',
                    title:'楼栋长'
                  },
                  {
                    index:'#22',
                    title:'综治领导责任制'
                  }
                ],
              },
            ],
          },
          {
            index:'#2',
            title:'特殊人群',
            subs:[
              {
                index:'/zongzhi/special/release',
                title:'刑满释放人员'
              },
              {
                index:'/zongzhi/special/correct',
                title:'社区矫正人员',
              },
              {
                index:'/zongzhi/special/drugs',
                title:'吸毒人员'
              },
              {
                index:'/zongzhi/special/psychosis',
                title:'精神病人员'
              },
              {
                index:'/zongzhi/special/aids',
                title:'艾滋病危险人员'
              },
            ]
          },
          {
            index:'#3',
            title:'社会治安',
            subs:[
              {
                index:'/zongzhi/socity/important_area',
                title:'重点地区排查整治',
              },
              {
                index:'/zongzhi/socity/check_renovate',
                title:'排查整治情况'
              },
              {
                index:'/zongzhi/socity/life_base',
                title:'命案基本信息',
              },
              {
                index:'/zongzhi/socity/life_commit',
                title:'命案犯罪嫌疑人',
              },
              {
                index:'/zongzhi/socity/logistics_safety',
                title:'寄递物流安全管理',
              },
              {
                index:'/zongzhi/socity/important_event',
                title:'重特大案(事)件',
              },
            ]
          },
          {
            index:'#4',
            title:'校园安全',
            subs:[
              {
                index:'/zongzhi/campus/school',
                title:'学校',
              },
              {
                index:'/zongzhi/campus/around',
                title:'校园周边重点人员'
              },
              {
                index:'/zongzhi/campus/teachers_safe',
                title:'涉及师生安全的案件',
              },
            ]
          },
          {
            index:'#5',
            title:'事件/矛盾纠纷',
            subs:[
              {
                index:'/zongzhi/dispute/found',
                title:'发现上报',
              },
              {
                index:'/zongzhi/dispute/accept_send',
                title:'受理派遣'
              },
              {
                index:'/zongzhi/dispute/deal_feedback',
                title:'处理反馈',
              },
              {
                index:'/zongzhi/dispute/task_check',
                title:'任务核查',
              },
              {
                index:'/zongzhi/dispute/finish_analysis',
                title:'结案分析',
              },
              {
                index:'/zongzhi/dispute/defer_audit',
                title:'延期审核',
              },
              {
                index:'/zongzhi/dispute/event_check',
                title:'事件查询',
              },
            ]
          },
          {
            index:'#6',
            title:'护路护线',
            subs:[
              {
                index:'/zongzhi/protect/road',
                title:'护路护线',
              },
              {
                index:'/zongzhi/include/road',
                title:'涉及线、路案(事)件'
              },
            ]
          },
          {
            index:'#7',
            title:'信访管理',
            subs:[
              {
                index:'/zongzhi/believe/account',
                title:'上访户',
              },
              {
                index:'/zongzhi/believe/petition_manage',
                title:'信访管理'
              },
            ]
          }
        ],
      }
    },
    mounted(){
      //解决页面刷新的时候路由不高亮显示的问题
      this.activeIndex=this.$route.matched[1].path;
    },
    components:{
      Aside
    }
  }
</script>
<style scoped>
</style>
